- hosts: docker
  vars_files:
  - varibles.yml
  tasks:
   - name: "Configuring yum for docker"
     yum_repository:
         name: "docker"
         description: "docker.repo"
         gpgcheck: no
         baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/" 
  
   - name: "Installing Docker"
     package:
        name: "docker-ce-18.09.1-3.el7.x86_64"
        state: present              
           
   - name: "Starting Docker Services"
     service:
        name: "docker"
        state: started

   - name: "Creating a directory for webserver"
     file:
        path: "/root/dockerserver"
        state: directory     

   - name: "Copying website file to the host"
     copy:
        src: "{{webpage}}"
        dest: "/root/dockerserver"

   - name: "Pulling httpd server image"
     docker_image:
         name: httpd
         source: pull     

   - name: "Launching Docker Container"
     docker_container: 
        name: "{{osname}}"
        image: "httpd"
        ports: 
           - "5000:80"
        state: started
        tty: yes
        volumes: "/root/dockerserver:/usr/local/apache2/htdocs/" 
        
